id: I8680B83C
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3879-final
source_file: null
initial_creation_type: input
imported: '2022-08-01T10:53:23.455615'
last_modified: '2022-08-01T10:53:23.455627'
parser: null
source_metadata:
  title: ཐུང་མོང་གི་རྩ་བ།
  base:
    F71D:
      title: ཐུང་མོང་གི་རྩ་བ།
      base_file: F71D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
